# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# pyright: reportMissingTypeStubs = false
from __future__ import annotations

import os
from collections.abc import Iterable
from enum import Flag
from typing import Optional
from typing import SupportsIndex

from jmcomic import JmApiClient
from jmcomic import JmHtmlClient


FILE_NAME_MAX_LENGTH: int = 255


class ExportFormat(Flag):
    folder = 1
    pdf = 2
    ip = 4


class Download:
    def __init__(self, album_ids: list[int]) -> None: ...
    def downloading(self, album_ids: list[int]) -> Download: ...
    def remove(self, id: int) -> Download: ...
    def pop(self, index: SupportsIndex = -1) -> Download: ...
    def add(self, id: int) -> Download: ...
    def insert(self, index: SupportsIndex, id: int) -> Download: ...
    def extend(self, ids: Iterable[int]) -> Download: ...
    def export_format(self, format: ExportFormat) -> Download: ...
    def add_export_format(self, format: ExportFormat) -> Download: ...
    def remove_export_format(self, format: ExportFormat) -> Download: ...
    def directory(self, directory: os.PathLike[str] | str) -> Download: ...
    def jpg(self, convert_to_jpg: bool = True) -> Download: ...
    def pictures(self, pictures: int) -> Download: ...
    def process(self) -> None: ...
    def process_download_cover(self, client: Optional[JmApiClient | JmHtmlClient] = None) -> None: ...   # noqa: E501
